### ISSUE TITLE
Chrome version?

### ISSUE THREAD

**Issue by Znunu** [machiavel23/BooruSlideshowRemake#6]
I'd like to use this fork as you seem to have fixed the issues with the gelbooru API. It says in the readme.md that this is for firefox. any way to get it working on chrome too?

**Comment by machiavel23** [comment]
> I'd like to use this fork as you seem to have fixed the issues with the gelbooru API. It says in the readme.md that this is for firefox. any way to get it working on chrome too?

Hello. Actually yes, it does work with chrome. Download the source zip file and in chrome, chose to install via zip file. There's a small bug however, clicking on booru slideshow will open 2 tabs for it. It's harmless, juste close one. You might need to enable dev mode on chrome to access the "install from zip" option.
You might also get a manifest warning at installation or first launch, it's just because the manifest file doesn't contain what chrome expects to find to identify the plugin, it's harmless too.

Note that this method also works on the Android browser Kiwi (and virtually any chromium based browser with the plugins options available) but it seems to randomly being uninstalled from it from time to time.

**Comment by Znunu** [comment]
Thanks a lot! I installed it, but i get an error with gelbooru

> No explicit, questionable or safe images were found.

**Comment by machiavel23** [comment]
You need to be logged in gelbooru for it to work.

**Comment by Znunu** [comment]
oh ok. i didnt know because i didn't have to previously. thanks

**Comment by Znunu** [comment]
doesn't seem to work
